# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49611bb15511ca4cb94b48f1eb1e302d2bd246904f2e9fa273bdeb895f344ddee0d3cffd954359e373b0d6924685040c77373d891a3b907bd35de796c6a1ba41

test:
  secret_key_base: 21c4e3ebe991474b0eded62685a2912a1fd783e0f9647937cabc2a0d7e24af68b2b97ee5f1bd0d58ff72e1e502e6faa4fa475fff0f4358533d2e1b3083d188e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
